version: "3"
services:
  redis:
    image: redis
    networks:
      - counter-net
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    networks:
      - counter-net
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - counter-net
networks:
  counter-net:
